### PR TITLE
Extended README.md for learning purposes

### PR DESCRIPTION
**Pull request by henkvancann**

### CODE REVIEW

**Comment by peacekeeper** [comment]
Thanks for offering to improve the README!

It looks like this adds some information which is specific to your own environment and probably won't work for anyone else, like: `cd /Users/hvc/apps/` or `hvc@Henks-Mbp20`.

Can you maybe change this to be more generic?

**Comment by henkvancann** [comment]
> Can you maybe change this to be more generic?
Yes, of course, when the time's ripe I'll do it, first things first :) ->  I just can't get the DID-Doc working yet in full:
https://github.com/peacekeeper/did-webs-iiw37-tutorial/issues/3

**Comment by henkvancann** [comment]
Pls wait until I've been able to confirm the working as described in the README.md

**Comment by peacekeeper** [comment]
I think this is generally useful. Few comments:

- I feel like the section "Your docker container is already up- and running?" is a bit redundant, since the tutorial starts with `docker compose down` anyway. But I guess it can help to have the extra section to explain it better just in case.
- Regarding the `https://weboftrust.github.io/WOT-terms/test/did-webs-iiw37-tutorial/` example, I would prefer to not mention the `raw.githubusercontent.com` approach. I think this is super confusing, and it would be better to properly use Github Pages instead.
- Other parts look great, e.g. I think they key rotation example is very helpful.

**Comment by henkvancann** [comment]
> I think this is generally useful. Few comments:
> 
> * I feel like the section "Your docker container is already up- and running?" is a bit redundant, since the tutorial starts with `docker compose down` anyway. But I guess it can help to have the extra section to explain it better just in case.
> * Regarding the `https://weboftrust.github.io/WOT-terms/test/did-webs-iiw37-tutorial/` example, I would prefer to not mention the `raw.githubusercontent.com` approach. I think this is super confusing, and it would be better to properly use Github Pages instead.
> * Other parts look great, e.g. I think they key rotation example is very helpful.

No worries, will change over the coming days. I do agree about github, I only had to change this,
 still.

**Comment by henkvancann** [comment]
> Pls wait until I've been able to confirm the working as described in the README.md

I think I've come to a point where this PR could be accepted already. 
Future PRs, I'll make in branches sprung off from main.

**Comment by henkvancann** [comment]
> * Regarding the `https://weboftrust.github.io/WOT-terms/test/did-webs-iiw37-tutorial/` example, I would prefer to not mention the `raw.githubusercontent.com` approach. I think this is super confusing, and it would be better to properly use Github Pages instead.
Agreed, I think I solved this elegantly enough here? ->
https://github.com/peacekeeper/did-webs-iiw37-tutorial/pull/4/commits/ffed50ea2f4d362fbbd0b5f2af4fbca1721fba1c

**Review by 2byrds — APPROVED** [review]
LGTM. Thank you @henkvancann

**Pull request merged**
